//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bezlio.rdb.plugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  [
                  {
                  'connectionName': 'Your Magento Site Name',
                  'siteUrl': 'http://demo20180315b.store.magecloud.net',
                  'consumerKey': '47aaefd47451a37d5815de825c3b1661',
                  'consumerSecret': 'c3cd7a0eee6df11cc6874aa5489a9335',
                  'magentoUserName': 'admin',
                  'magentoUserPassword': '33oOekhhBZoWKU4ndEWp'
                  }
                  ]
                ")]
        public string connections {
            get {
                return ((string)(this["connections"]));
            }
        }
    }
}
