//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bezlio.rdb.plugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  [
                  {
                  'locationName': 'Friendly Name',
                  'locationPath': 'C:\\Path\\Queries\\'
                  },
                  {
                  'locationName': 'Another Friendly Name',
                  'locationPath': 'C:\\Different Path\\Queries\\'
                  }
                  ]
                
")]
        public string sqlFileLocations {
            get {
                return ((string)(this["sqlFileLocations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  [
                  {
                  'connectionName': 'Friendly Connection Name',
                  'serverAddress': 'SQL_SERVER',
                  'databaseName': 'DATABASE_NAME',
                  'userName': 'SQL_USER_NAME',
                  'password': 'SQL_USER_PASSWORD'
                  }
                  ]
                ")]
        public string connections {
            get {
                return ((string)(this["connections"]));
            }
        }
    }
}
