//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bezlio.rdb.plugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  [
                  {
                  'connectionName': 'Production',
                  'appServerUrl': 'net.tcp://YOUR_APP_SERVER_NAME/YOUR_INSTANCE',
                  'userName': 'YOUR_EPICOR_LOGIN',
                  'password': 'YOUR_EPICOR_PASSWORD'
                  },
                  {
                  'connectionName': 'Test',
                  'appServerUrl': 'net.tcp://YOUR_APP_SERVER_NAME/YOUR_INSTANCE',
                  'userName': 'YOUR_EPICOR_LOGIN',
                  'password': 'YOUR_EPICOR_PASSWORD'
                  },
                  {
                  'connectionName': 'Training',
                  'appServerUrl': 'net.tcp://YOUR_APP_SERVER_NAME/YOUR_INSTANCE',
                  'userName': 'YOUR_EPICOR_LOGIN',
                  'password': 'YOUR_EPICOR_PASSWORD'
                  }
                  ]
                
")]
        public string connections {
            get {
                return ((string)(this["connections"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Epicor\\ERP10.0Client\\Client")]
        public string epicorClientPath {
            get {
                return ((string)(this["epicorClientPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string epicorConfigName {
            get {
                return ((string)(this["epicorConfigName"]));
            }
        }
    }
}
