//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bezlio.rdb.plugins.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  [
                  {
                  'connectionName': 'Epicor 905 Live',
                  'appServerUrl': 'AppServerDC://SL-EPICOR:9401',
                  'userName': 'manager',
                  'password': 'manager'
                  },
                  {
                  'connectionName': 'Epicor 905 Training',
                  'appServerUrl': 'AppServerDC://SL-EPICOR:9411',
                  'userName': 'manager',
                  'password': 'manager'
                  }
                  ]
                ")]
        public string connections {
            get {
                return ((string)(this["connections"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Epicor\\Epicor905\\Client\\")]
        public string epicorClientPath {
            get {
                return ((string)(this["epicorClientPath"]));
            }
        }
    }
}
